---
- name: "configuration play." 
  hosts: web
  user: ubuntu
  gather_facts: false
  vars:
    - ansible_python_interpreter: /usr/bin/python3
    - ansible_host_key_checking: false
    - ansible_stdout_callback: yaml
    - ENVIRONMENT: "production"
    - NODE_ENV: "production"
    - TYPEORM_ENTITIES: "./src/modules/domain/**/*.entity.ts"
    - TYPEORM_MIGRATIONS: "./src/migrations/*.ts"
    - TYPEORM_MIGRATIONS_DIR: "./src/migrations"
    - TYPEORM_CONNECTION: "postgres"
    - TYPEORM_HOST: "{{ lookup('env', 'TYPEORM_HOST') }}"
    - TYPEORM_PORT: "{{ lookup('env', 'TYPEORM_PORT') }}"
    - TYPEORM_DATABASE: "{{ lookup('env', 'TYPEORM_DATABASE') }}"
    - TYPEORM_USERNAME: "{{ lookup('env', 'TYPEORM_USERNAME') }}"
    - TYPEORM_PASSWORD: "{{ lokup('env', 'TYPEORM_PASSWORD') }}"
  pre_tasks:
    - name: "wait 600 seconds for target connection to become reachable/usable."
      wait_for_connection:
        delay: 20
        timeout: 60
    - name: "install python for Ansible."
      become: true
      raw: test -e /usr/bin/python3 || (apt -y update && apt install -y python3)
      changed_when: false
    - setup:
  roles:
    - configure-server
    - configure-prometheus-node-exporter