---
- name: "download"
  become: true
  command: curl -sL https://deb.nodesource.com/setup_13.x | sudo -E bash -
  args:
    chdir: /root
- name: "upgrade"
  become: true
  command: apt-get install -y nodejs
  args:
    chdir: /root
- name: "install pm2"
  become: true
  npm:
    name: pm2
    global: yes
    production: yes
    state: present

- name: Creates directory
  file:
    path: /home/ubuntu/backend
    state: directory

- name: Copy artifact.tar.gz file
  become: true
  copy:
    src: /root/project/artifact.tar.gz
    dest: /home/ubuntu/backend
    force: no

- name: Uncompressed Backend
  shell: |
    cd /home/ubuntu/backend
    tar xvzf artifact.tar.gz -C .
    ls -la
- name: Build
  become: true
  shell: |
    cd /home/ubuntu/backend
    npm install
    npm run build
- name: Start PM2
  become: true
  shell: |
    cd /home/ubuntu/backend
    sudo pm2 start npm --name backend -- start